### ISSUE TITLE
是否可以支持显示时转换，但不保存到文件

### ISSUE THREAD

**Issue by Kurt-Shiwz** [huanz/vscode-GBKtoUTF8#4]
hi，是否可以支持只在显示时转换，但不保存到文件，因为我不能修改文件编码。^_^

**Comment by iseeyo** [comment]
支持下，每次都提示保存也是挺麻烦的

**Comment by huanz** [comment]
@Kurt-Shiwz @iseeyo 查了下接口，没找到好的方案啊

**Comment by Kurt-Shiwz** [comment]
> @Kurt-Shiwz @iseeyo 查了下接口，没找到好的方案啊

我都从上家公司离职了。。。

**Comment by huanz** [comment]
@Kurt-Shiwz 哈哈哈，不知道目前vscode还有没有gbk的问题了，刚发现新建个隐藏的零时文件可以解决
